/**:
  ros__parameters:
    cmd_freq: 100.0  # Hz (default: 100.0)
    info_freq: 10.0  # Hz (default: 10.0)
    odom_frame: "odom"  # (default: odom)
    base_frame: "base_link"  # (default: base_link)