/**:
  ros__parameters:
    simulation_params:
      simulator_update_freq: 100.0  # Hz (default: 100.0)
      simulator_state_pub_freq: 30.0  # Hz (default: 30.0)
      floor_height: 0.0
      # State
      vehicle_initial_pose:
        x: 0.0
        y: 0.0
        z: 0.0
        roll: 0.0
        pitch: 0.0
        yaw: 0.0
      