/**:
  ros__parameters:
    quadrotor_params:
      # Model Parameters
      motor_thrust_coefficient: 1.91e-6
      motor_torque_coefficient: 2.6e-7
      motor_dx: 0.08
      motor_dy: 0.08
      motors_frame_type: 1 # 0: +-Configuration, 1: X-Configuration
      motor_min_speed: 0.0
      motor_max_speed: 2200.0
      motor_time_constant: 0.02
      motor_rotational_inertia: 6.62e-6
      vehicle_mass: 1.0
      vehicle_inertia:
        ixx: 0.0049
        iyy: 0.0049
        izz: 0.0069
      vehicle_drag_coefficient: 0.1
      vehicle_aero_moment_coefficient:
        ixx: 0.003
        iyy: 0.003
        izz: 0.003
      gravity: 9.81
      moment_process_noise_auto_correlation: 1.25e-7
      force_process_noise_auto_correlation: 0.0005
      # Controller Parameters
      antiwindup_cte: 1500.0
      alpha: 0.4
      flight_controller:
        kp:
          x: 10.0
          y: 10.0
          z: 10.0
        ki:
          x: 6.0
          y: 6.0
          z: 6.0
        kd:
          x: 0.02
          y: 0.02
          z: 0.02
      # IMU Parameters
      imu:
        gyro_noise_var: 0.003
        accel_noise_var: 0.005
        gyro_bias_noise_autocorr_time: 1.0e-7
        accel_bias_noise_autocorr_time: 1.0e-7
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0
